name: node CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: npm ci
      - run: npm test
        env:
          JWT_SECRET: xdd
